[supervisord]
nodaemon=true

[program:backend]
directory=/app/packages/backend
command=npm run start
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:frontend]
directory=/app/packages/frontend
command=npm run start -- -p 3000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true