[supervisord]
nodaemon=true

[program:backend]
directory=/app/packages/backend
command=sh -c "npx prisma migrate deploy && npm run start"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:frontend]
directory=/app/packages/frontend
command=npm run start -- -p 3000
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
